// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDnoE7UDNG7Tz_f7KWoJD17fntwfsJAxs',
    appId: '1:467091157072:web:4d665e68925e318ed26155',
    messagingSenderId: '467091157072',
    projectId: 'todo-app-a7d74',
    authDomain: 'todo-app-a7d74.firebaseapp.com',
    storageBucket: 'todo-app-a7d74.appspot.com',
    measurementId: 'G-NL3Q16XVW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChflEi2tjke_j2novhgmwGDxAmvPRT4mw',
    appId: '1:467091157072:android:de0ea02152eedd95d26155',
    messagingSenderId: '467091157072',
    projectId: 'todo-app-a7d74',
    storageBucket: 'todo-app-a7d74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoLM9kz5IGIYR1TelR19nMjuzW7FESAuw',
    appId: '1:467091157072:ios:671c5d37b907ec25d26155',
    messagingSenderId: '467091157072',
    projectId: 'todo-app-a7d74',
    storageBucket: 'todo-app-a7d74.appspot.com',
    iosClientId: '467091157072-283nr0u1ubluvg3sod0rr7ol2hjiqcqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoLM9kz5IGIYR1TelR19nMjuzW7FESAuw',
    appId: '1:467091157072:ios:671c5d37b907ec25d26155',
    messagingSenderId: '467091157072',
    projectId: 'todo-app-a7d74',
    storageBucket: 'todo-app-a7d74.appspot.com',
    iosClientId: '467091157072-283nr0u1ubluvg3sod0rr7ol2hjiqcqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
